language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
  - ./.scripts/create-maven-settings.sh
  - sudo apt-get update
install:
  - sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0
script:
  - mvn clean verify
after_success:
  - ./.scripts/deploy-site.sh
  - ./.scripts/deploy.sh
