language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
  - ./.scripts/create-maven-settings.sh
install:
  - sudo apt-get -qq --force-yes install ia32-libs ia32-libs-multiarch
script:
  - mvn clean verify
after_success:
  - ./.scripts/deploy-site.sh
  - ./.scripts/deploy.sh
